### ISSUE TITLE
Create Meta-review v1

### ISSUE THREAD

**Issue by CooperSmout** [openheartmind/WISDOM#108]
Prototype edits:
- [x] Increase batch size of review contributions (to compensate for smaller baseline unit), delete the smallest review contribution (shown to be too small in the original dataset), round off to nearest 100/1000 for simplicity:
  - Previous range: [16, 32, 64, 128, 256, 512, 1024, 2048]
  - New range = [100, 200, 500, 1000, 2000, 5000, 10000]
- [x] Simplify pairing mechanism as per "WISDOM x Vibeclipse" prototype
- [x] Add 5 alternative dimensions to META-REVIEW tab (I also considered creating new tabs for each dimension but decided it would be weird having a different format to the REVIEW tab)
- [x] Update review contribution descriptions to refer to individual pairwise comparisons

Questions for the team:
- Should we display an 'average duration' for review contributions?

**Comment by CooperSmout** [comment]
After doing all this, realised that the review batch sizes will vary by dimension, so it's not as simple as 

Also not how we planned the study in the first place. After discussion with the team decided to leave this until after AIMOS2024. 

So we had a clean prototype to present at AIMOS2024, I undid most of this work using GSheets version history. 

We've now decided to write-up the prototype study as a preprint, and agreed we should change the baseline scaling and redo meta-reviews after all, otherwise it will be confusing in the literature (but leaving alternative dimensions as is).
